---
title: "Asn-1"
author: "Tegen Hilker Readman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r downloadLibs}
#Downloading the libraries needed
library(kableExtra)
library(readxl)
library(janitor)
library(tidyverse)
library(lubridate)
library(scales)
library(viridis)

```

```{r download data-}
if (!file.exists('can_net_zero.csv'))
    download.file("https://www.cer-rec.gc.ca/open/energy/energyfutures2023/benchmark-prices-2023.csv",destfile =  'can_net_zero.csv',mode = "wb")

can_net_zero<-read_csv("can_net_zero.csv")%>%clean_names()
```
```{r deliverable 1}
wcs_data<-can_net_zero%>%filter(variable=="Western Canadian Select (WCS) - 2022 US$/bbl")%>%
  filter(year%%5==0)%>%
  filter(scenario=="Canada Net-zero")%>%
  select(year,value)%>%
  filter(year>=2020)%>% mutate(value = round(value, 2))

  
wcs_data %>%
  kbl(escape = FALSE,table.attr = "style='width:80%;'",digits=2,align=rep('c', 2)) %>%
  kable_styling(fixed_thead = T,bootstrap_options = c("hover", "condensed","responsive"),full_width = T)%>%
  add_header_above(header = c("Western Canada Select (WCS) prices in the Canada Net-Zero scenario of the Canadian Energy Regulator's Canada's Energy Future (2023) report"=2))

```
